// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ndeCD25KPPqO2ImPvjjAY9Gr6QFC9wE',
    appId: '1:685343143928:web:94b20553b2a40c31a8c80d',
    messagingSenderId: '685343143928',
    projectId: 'auditore-a6b13',
    authDomain: 'auditore-a6b13.firebaseapp.com',
    storageBucket: 'auditore-a6b13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6b2qabp-DhBK6UfZgoppePS2EEeUnV7o',
    appId: '1:685343143928:android:7ef85a55e1736b12a8c80d',
    messagingSenderId: '685343143928',
    projectId: 'auditore-a6b13',
    storageBucket: 'auditore-a6b13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHdeHSF-e_wsgA-WWvjyC4YOhBf_eMBlA',
    appId: '1:685343143928:ios:c30a72618a9a388fa8c80d',
    messagingSenderId: '685343143928',
    projectId: 'auditore-a6b13',
    storageBucket: 'auditore-a6b13.appspot.com',
    iosClientId: '685343143928-nh49favluobqhmjkpbhh4q59jp0ojmqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.auditoreV4',
  );
}
